version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.2
    - 4.16.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: "@sentry/node"
    versions:
    - 5.29.2
    - 6.0.4
    - 6.2.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
